steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install','-g', 'vuepress']
- name: 'gcr.io/cloud-builders/npm'
  args: [ 'run','docs:build' ]
- name: 'gcr.io/vuepress-e0b13/firebase'
  args: [ 'deploy', '--token', '${_FIREBASETOKEN}']
images:
- 'gcr.io/vuepress-e0b13/firebase'
