steps:
- name: 'gcr.io/vuepress-e0b13/vuepress'
  args: [ 'build', 'docs' ]
- name: 'gcr.io/vuepress-e0b13/firebase'
  args: [ 'deploy', '--token', '${_FIREBASETOKEN}']
images:
- 'gcr.io/vuepress-e0b13/firebase'
- 'gcr.io/vuepress-e0b13/vuepress'
